### ISSUE TITLE
Non-descriptive exceptions when reloading checkpoints

### ISSUE THREAD

**Issue by BatchDrake** [parmoo/parmoo#50]
Hi,

I am attempting to load a previous checkpoint with Parmoo (version 0.2.0) but I am getting this obscure exception instead. This is what happens when I call `moop.load(file)` 

```
Traceback (most recent call last):
  File "/home/waldo/Documents/Documentos/CBandV2/Hairpin/BetterOptim/parmoo-refms.py", line 296, in <module>
    parmoo_optimize(filter)
  File "/home/waldo/Documents/Documentos/CBandV2/Hairpin/BetterOptim/parmoo-refms.py", line 283, in parmoo_optimize
    moop.load(FILTER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/parmoo/moop.py", line 2615, in load
    obj_ptr = getattr(mod, obj_name)
AttributeError: module '__main__' has no attribute '<lambda>'
```
The `refmicrostrip.moop` and `refmicrostrip.surrogate.1` files exist (see attachments):

[refmicrostrip.moop.txt](https://github.com/parmoo/parmoo/files/10843325/refmicrostrip.moop.txt)
[refmicrostrip.surrogate.1.txt](https://github.com/parmoo/parmoo/files/10843326/refmicrostrip.surrogate.1.txt)

And this is how I am initializing the MOOP object:

```python
    moop = MOOP(LocalGPS)

    params = filter.get_param_list()
    bounds = filter.get_full_bounds()

    # Add all params
    for i in range(len(params)):
        moop.addDesign(
            {
                'name':     params[i],
                'des_type': 'continuous',
                'lb':       bounds.lb[i],
                'ub':       bounds.ub[i]
            })

    moop.addSimulation(
        {
            'name': "FilterSim",
            'm': 2,
            'sim_func': chrosen,
            'search': LatinHypercube,
            'surrogate': GaussRBF,
            'hyperparams': {'search_budget': 20}
        })
    
    moop.addObjective(
        {'name': 'Score', 'obj_func': lambda x, s: sum(s['FilterSim'])}
    )

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)-8s %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S')

    moop.load(FILTER_NAME)
```

**Comment by thchang** [comment]
Making a note that we should remove lambda functions from the quickstart demo to prevent further confusion in the future.  This issue will remain open until we have done so.
